// import type { Metadata } from "next";
// import "./globals.css";
// import { Heebo } from "next/font/google";
// import { Navbar, Footer } from "@/components/";
// import { ThemeProvider } from "./provider";

// const font = Heebo({
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (

//     <html lang="en" suppressHydrationWarning>
//     <body className={inter.className}>
//       <ThemeProvider>{children}</ThemeProvider>
//       <Navbar />
 
//  <Footer />
//     </body>
//   </html>


//   );
// }


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";

// import "./globals.css";
// import { ThemeProvider } from "./provider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Portfolio | Your Name",
//   description: "Modern portfolio website",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={inter.className}>
//         <ThemeProvider>{children}</ThemeProvider>
//       </body>
//     </html>
//   );
// }



import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}